import { StyleSheet } from 'react-native';

export const createStyles = (theme) => {
    if (!theme || typeof theme !== 'object' || theme === null) {
        console.log("Theme: ", theme);
        throw new TypeError('Invalid theme object');
    }

    return StyleSheet.create({
        pageContainer: {
            flex: 1,
            backgroundColor: theme.background,
        },
        container: {
            flexGrow: 1,
            alignItems: 'center',
            paddingVertical: 10,
        },
        header: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingHorizontal: 16,
            paddingVertical: 12,
            borderBottomWidth: 1,
            borderBottomColor: theme.border,
            backgroundColor: theme.primary,
        },
        draggablesContainer: {
            width: '100%',
            paddingHorizontal: 16,
        },
        draggable: {
            width: '100%',
            height: 54,
            backgroundColor: theme.primary,
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 16,
            marginVertical: 4,
            borderRadius: 8,
            borderWidth: 1,
            borderColor: theme.border,
        },
        folderContainer: {
            width: '100%',
            paddingHorizontal: 16,
            marginBottom: 8,
        },
        folderHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            backgroundColor: theme.primLight,
            padding: 16,
            borderRadius: 8,
            borderWidth: 1,
            borderColor: theme.border,
        },
        folder: {
            marginTop: 8,
            backgroundColor: theme.primary,
            borderRadius: 8,
            borderWidth: 1,
            borderColor: theme.border,
        },
        modalBackground: {
            flex: 1,
            justifyContent: 'flex-end',
            backgroundColor: theme.modalOverlay,
        },
        modalContent: {
            backgroundColor: theme.primary,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            padding: 20,
            paddingBottom: 34,
        },
        input: {
            width: '100%',
            height: 44,
            backgroundColor: theme.primLight,
            borderRadius: 6,
            paddingHorizontal: 12,
            marginVertical: 8,
            color: theme.text,
            borderWidth: 1,
            borderColor: theme.border,
        },
        button: {
            backgroundColor: theme.accent,
            borderRadius: 6,
            paddingVertical: 12,
            alignItems: 'center',
            marginTop: 16,
        },
        buttonText: {
            color: '#ffffff',
            fontWeight: '600',
            fontSize: 16,
            textAlign: 'center',
        },
        normalText: {
            color: theme.text,
            fontSize: 16,
            marginBottom: 16,
        },
        themeButton: {
            padding: 8,
            borderRadius: 8,
            backgroundColor: theme.primLight,
            borderWidth: 1,
            borderColor: theme.border,
        },
        icon: {
            width: 24,
            height: 24,
            tintColor: theme.text,
        },
        feedTitle: {
            fontSize: 16,
            fontWeight: '600',
            color: theme.text,
            marginLeft: 12,
        },
        feedIcon: {
            width: 32,
            height: 32,
            borderRadius: 16,
            backgroundColor: theme.primLight,
        },
        feedCard: {
            backgroundColor: theme.primary,
            borderBottomWidth: 1,
            borderBottomColor: theme.border,
            padding: 16,
        },
        feedHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 8,
        },
        feedHeaderLeft: {
            flexDirection: 'row',
            alignItems: 'center',
            flex: 1,
        },
        feedIcon: {
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: theme.accent,
            justifyContent: 'center',
            alignItems: 'center',
            marginRight: 12,
        },
        feedIconText: {
            color: '#ffffff',
            fontSize: 18,
            fontWeight: '600',
        },
        feedTitleContainer: {
            flex: 1,
        },
        feedTitle: {
            fontSize: 16,
            fontWeight: '600',
            color: theme.text,
            marginBottom: 2,
        },
        feedDate: {
            fontSize: 12,
            color: theme.secondaryText,
        },
        feedPreview: {
            fontSize: 14,
            color: theme.secondaryText,
            marginTop: 4,
            lineHeight: 20,
        },
        chevron: {
            fontSize: 24,
            color: theme.secondaryText,
            marginLeft: 8,
        },
        articleHeader: {
            backgroundColor: theme.primary,
            borderBottomWidth: 1,
            borderBottomColor: theme.border,
            padding: 16,
        },
        titleContainer: {
            gap: 4,
        },
        articleTitle: {
            fontSize: 20,
            fontWeight: '600',
            color: theme.text,
            lineHeight: 28,
        },
        linkText: {
            fontSize: 12,
            color: theme.secondaryText,
        },
        contentContainer: {
            flex: 1,
            padding: 16,
        },
        articleText: {
            fontSize: 16,
            lineHeight: 24,
            color: theme.text,
        },
        articleImage: {
            borderRadius: 8,
            marginVertical: 12,
        },
        bottomToolbar: {
            flexDirection: 'row',
            borderTopWidth: 1,
            borderTopColor: theme.border,
            backgroundColor: theme.primary,
            paddingVertical: 8,
            paddingHorizontal: 16,
            gap: 16,
        },
        toolbarButton: {
            padding: 8,
            borderRadius: 8,
            backgroundColor: theme.primLight,
        },
        toolbarButtonActive: {
            backgroundColor: theme.accent,
        },
        toolbarIcon: {
            width: 24,
            height: 24,
            tintColor: theme.text,
        },
        toolbarIconActive: {
            tintColor: '#ffffff',
        },
        modalBackground: {
            flex: 1,
            justifyContent: 'flex-end',
            backgroundColor: theme.modalOverlay,
        },
        modalContent: {
            backgroundColor: theme.primary,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            maxHeight: '80%',
        },
        modalHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            padding: 16,
            borderBottomWidth: 1,
            borderBottomColor: theme.border,
        },
        modalTitle: {
            fontSize: 16,
            fontWeight: '600',
            color: theme.text,
        },
        modalCloseButton: {
            padding: 4,
        },
        modalCloseText: {
            fontSize: 24,
            color: theme.text,
            fontWeight: '400',
        },
        modalText: {
            padding: 16,
            fontSize: 16,
            lineHeight: 24,
            color: theme.text,
        },
        themeContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: 20,
            paddingVertical: 10,
            alignContent: 'center',
            textAlign: 'center',
        },
        logoutButton: {
            backgroundColor: "#f60021",
            padding: 12,
            borderRadius: 6,
            alignItems: 'center',
            width: '90%',
        },
        logoutText: {
            color: '#ffffff',
            fontSize: 20,
            fontWeight: 'bold',
        },
        link: {
            color: theme.link,
        },
        addButtonContainer: {
            position: 'absolute',
            bottom: 24,
            right: 24,
            zIndex: 1000,
        },
        addButton: {
            width: 56,
            height: 56,
            borderRadius: 28,
            backgroundColor: theme.accent,
            justifyContent: 'center',
            alignItems: 'center',
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.25,
            shadowRadius: 3.84,
            elevation: 5,
        },
        addButtonText: {
            color: '#ffffff',
            fontSize: 32,
            fontWeight: '300',
            marginTop: -2,
        },
        addFeedButton: {
            backgroundColor: theme.accent,
            paddingVertical: 12,
            paddingHorizontal: 24,
            borderRadius: 6,
            alignItems: 'center',
        },
        toggleContainer: {
            padding: 15,
            borderTopWidth: 1,
            borderTopColor: theme.border,
            flexDirection: 'row',
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: theme.primary,
        },
        modalSelect: {
            backgroundColor: theme.accent,
            padding: 12,
            borderRadius: 8,
            borderWidth: 1,
            borderColor: theme.border,
            textAlign: 'center',
            marginVertical: 8,
        },
        modalPrompt: {
            fontSize: 16,
            color: theme.text,
            marginBottom: 8,
            textAlign: 'center',
        },
    });
};
